channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - dask=2026.6.0
  - distributed=2026.6.0
  - flatten_json
  - numpy=2.3.5
  - ome-zarr-models=1.7
  - pydantic>=2.11.5
  - pyyaml
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - toolz=1.1.0
  - zarr=3.2.1
  - tornado
  - pip:
    - xarray-multiscale==2.1.0
