channels:
  - conda-forge
dependencies:
  - python=3.12
  - c-blosc2
  - dask=2025.11.0
  - distributed=2025.11.0
  - pip
  - flatten_json
  - imagecodecs
  - numcodecs=0.16.1
  - numpy=2.3.5
  - ome-zarr-models=1.3
  - pydantic=2.12.4
  - pyyaml
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - toolz=1.1.0
  - zarr=3.1.5
  - tornado
  - pip:
    - xarray-multiscale==2.1.0
